[package]
name = "vinx"
version = "0.1.0"
authors = ["Revertron <revertron@revertron.com>"]

[dependencies]
quick-xml = "0.22.0"
downcast-rs = "1.2.0"
speedy2d = { version = "1.1.2", path = "../Speedy2D" }
include_dir = "0.6.2"